### ISSUE TITLE
Japanese.lproj and others remain after running ( system preferences removed all except english)

### ISSUE THREAD

**Issue by DG12** [IngmarStein/Monolingual#87] opened 2016-09-04 01:36 UTC
After running 
/Applications > find . -name Japanese.lproj -ls |wc
      53     618    8491

i.e. there are 53 occurrences of the  Japanese.lproj  in the Applications directory.

I expected these to be deleted. 
I changed system/preferences/language+Region to only have english and
checked all boxes in monolingual except english and english(United States)

syslog warning includes many blacklist URL (reversed) (perhaps they shouldn't be level warning?)
as well as Adding root Applications, Library, excluding root/system root/bin 
com.github.IngmarStein.Monolingual.Helper[66649]: exiting with exit status 0
closed connection to helper,
XPC connection  to helper invalidated.
---and that's it 
nothing more in debug/info or notice

PS it seems that monolingual must run from /Applicaitons i.e. not /Users/me/bin.

Thank you for your efforts.

**Comment by IngmarStein** [comment] 2016-09-04 18:58
Duplicate of #84.

**Comment by DG12** [comment] 2016-09-05 00:52
> csrutil status 
System Integrity Protection status: disabled.

**Comment by IngmarStein** [comment] 2016-09-05 16:52
Sorry for closing so quickly. Many people are confused by SIP and blame Monolingual for not removing files…

**Comment by IngmarStein** [comment] 2016-09-05 19:03
Maybe the SIP check is broken. What's the result of `sudo mkdir /System/Monolingual.sip` on your system? `Operation not permitted` or success?

**Comment by DG12** [comment] 2016-09-06 00:17
> sudo ls -ld Monolingual.sip
        drwxr-xr-x  2 root  wheel  68 Sep  5 20:01 Monolingual.sip
        
        /System > sudo ls -la Monolingual.sip
        total 0
        drwxr-xr-x  2 root  wheel   68 Sep  5 20:01 .
        drwxr-xr-x@ 5 root  wheel  170 Sep  5 20:01 ..
        
        / > sudo rmdir /System/Monolingual.sip/
        Password:
        / > sudo rmdir /System/Monolingual.sip/
        rmdir: /System/Monolingual.sip/: No such file or directory
        
      Note however
        / > ls -ld@ /System 
          drwxr-xr-x@ 5 root  wheel  170 Sep  5 20:01 /System/
              com.apple.rootless      0 
      Although I dont think we care.
      
        Actually,
          checkRootles
          is a bit of a misnomer as it really checks the ability to
          create and remove /System/Monolingual.sip
        
      In any case please add NSlog
        stating  what
          happened.
          
          Thanks again,
          Dennis
        
      
      
      
        // check if SIP is enabled, see
        https://github.com/IngmarStein/Monolingual/issues/74
            func checkRootless() -> Bool {
                let protectedDirectory = NSURL(fileURLWithPath:
        "/System/Monolingual.sip", isDirectory: true)
                let fileManager = NSFileManager.defaultManager()
        
                do {
                    #if swift(>=3.0)
                    try fileManager.createDirectory(at:
        protectedDirectory, withIntermediateDirectories: false,
        attributes: nil)
                    #else
                    try
        fileManager.createDirectoryAtURL(protectedDirectory,
        withIntermediateDirectories: false, attributes: nil)
                    #endif
                } catch {
                    return true
                }
        
                do {
                    #if swift(>=3.0)
                    try fileManager.removeItem(at: protectedDirectory)
                    #else
                    try fileManager.removeItemAtURL(protectedDirectory)
                    #endif
                } catch let error as NSError {
                    NSLog("Failed to remove temporary file '%@': %@",
        protectedDirectory, error)
                }
        
                return false
            }
      
      On 9/5/16 3:03 PM, Ingmar Stein wrote:
    
    sudo mkdir /System/Monolingual.sip

**Comment by IngmarStein** [comment] 2016-09-06 05:24
`checkRootless` tries to determine if SIP is enabled by creating a directory in a place that is known to be protected by SIP. The directory serves no other purpose and should be deleted right after that.

The result is printed in `Helper.init()` (work is currently done only in the `swift3` branch):
```
		isRootless = checkRootless()
		os_log("isRootless=%@", type: .debug, isRootless ? "true" : "false")
```
So it seems like we're able to create but not to delete the directory… In which case any subsequent `FileManager.createDirectory(at:, withIntermediateDirectories:, attributes:)` calls fail and Monolingual thinks that SIP is turned on.

**Comment by DG12** [comment] 2016-09-06 15:31
Thanks for your continued followup. 
Sorry for the confusion.
/System/Monolingual.sip existed at "Sep  5 20:01" because I created it manually (as you requested 9/5/16 3:03 PM)

Tried again, 
/Users/dgerman > date
Tue Sep  6 10:48:18 EDT 2016
/Users/dgerman > ls -l /System/Monolingual.sip
ls: /System/Monolingual.sip: No such file or directory
/Users/dgerman > open /Applications/Monolingual.app
/Users/dgerman > ls -l /System/Monolingual.sip
ls: /System/Monolingual.sip: No such file or directory    ## a good thing
/Users/dgerman > tail /var/log/07*g
Sep  6 10:48:52 smackerpro Monolingual[59690]: [Crashlytics] Version 3.7.0 (102)
Sep  6 10:48:52 smackerpro XPCKeychainSandboxCheck[59728]: Can't get sandbox fs extension for /Users/dgerman/Library/Preferences/com.apple.security.plist
Sep  6 10:48:53 smackerpro Monolingual[59690]: 
Sep  6 10:49:03: --- last message repeated 6 times ---     ## not sure why this is ###
Sep  6 10:49:03 smackerpro Monolingual[59690]: LSExceptions [0x7faad8d1d920] unloaded

---  List of languages had been retained from previous run
--- tic,tic,tic  ... "Files removed. Space saved:Zero KB."

/Users/dgerman > tail /var/log/07*g
Sep  6 10:50:24 smackerpro com.github.IngmarStein.Monolingual.Helper[61084]: exiting with exit status 0
Sep  6 10:50:25 smackerpro Monolingual[59690]: Closing connection to helper
Sep  6 10:50:25 smackerpro Monolingual[59690]: XPC connection to helper invalidated.
Sep  6 10:50:25 smackerpro usernoted[278]: 
Sep  6 10:50:32 smackerpro Dock[265]: [default] List identifier: com.apple.LSSharedFileList.ApplicationRecentDocuments/com.github.IngmarStein.Monolingual
Sep  6 10:50:32 smackerpro Dock[265]: -[SFLListManager removeList:] List identifier: com.apple.LSSharedFileList.ApplicationRecentDocuments/com.github.IngmarStein.Monolingual
Sep  6 10:50:32 smackerpro Dock[265]: [default] Unsubscribe from list with identifier com.apple.LSSharedFileList.ApplicationRecentDocuments/com.github.IngmarStein.Monolingual
Sep  6 10:50:32 smackerpro Dock[265]: __29-[SFLListManager removeList:]_block_invoke Unsubscribe from list with identifier com.apple.LSSharedFileList.ApplicationRecentDocuments/com.github.IngmarStein.Monolingual
Sep  6 10:50:32 smackerpro sharedfilelistd[276]: [default] <CFString 0x7fdac1c1b120 [0x7fff7e684440]>{contents = "com.apple.dock"}[265] unsubscribed from list <CFString 0x7fdac1d47dc0 [0x7fff7e684440]>{contents = "com.apple.LSSharedFileList.ApplicationRecentDocuments/com.github.IngmarStein.Monolingual"}
Sep  6 10:50:32 smackerpro sharedfilelistd[276]: -[ConnectedProcess(SFLServiceProtocol) unsubscribeToListWithIdentifier:] com.apple.dock[265] unsubscribed from list com.apple.LSSharedFileList.ApplicationRecentDocuments/com.github.IngmarStein.Monolingual


PS  do you delete 
/System/Library/LinguisticData  ??  
May you could also add:
/System/Library/Speech/Sin-ji, Kyoto, Carmit(?), Zuzana(?)
See http://real-world-systems.com/docs/say.1.html

I don't do swift, but maybe I'll give it a try. 
So far I'm having a little trouble locating the API docs for    NSlog.


Later.

**Comment by IngmarStein** [comment] 2016-09-08 09:08
I justed tested `checkRootless()` on a system with SIP disabled and it seems to return the correct value, so I guess the error is somewhere else.

Monolingual doesn't delete any files in `/System/Library/LinguisticData` or `/System/Library/Speech`.

**Comment by IngmarStein** [comment] 2016-09-09 13:48
Can you please give me an example of a file which you think should be deleted and is not?

Some system language files are not removed by Monolingual because they're part of a code signature and deleting them would break the signature.
An arbitrary example is `/System/Library/PrivateFrameworks/PrintingPrivate.framework/Versions/A/Plugins/PrintingCocoaPDEs.bundle/Contents/Resources/vi.lproj/SummaryPDE.strings` which is listed in `/System/Library/PrivateFrameworks/PrintingPrivate.framework/Versions/A/_CodeSignature/CodeResources` as a non-optional resource.

**Comment by DG12** [comment] 2016-09-09 22:51
Massive > 6MB FONT files (does this want to be a new topic?


ヒラギノ丸ゴ ProN W4.ttc
儷宋 Pro.ttf
儷黑 Pro.ttf

**Comment by DG12** [comment] 2016-09-10 03:09
cd /Applications 
 find . -name pt.lproj -ls |wc
     152    1805   25946
 find . -name es.lproj -ls |wc
      98    1174   17584
find . -name ko.lproj -ls |wc
     151    1792   25757

**Comment by IngmarStein** [comment] 2016-09-10 07:01
This topic is getting messy.

Speech files: please open a new feature request
Font files: please open a new feature request.
Linguistic data: please open a new feature request
API docs for NSLog: Google found it here: https://developer.apple.com/reference/foundation/1409759-nslog

Now back to the topic: please provide some (~ 5) file names that you expect to be deleted, not the total count. As I mentioned, it is expected that many remain because of code signatures.

**Comment by DG12** [comment] 2016-09-10 14:48
executables are being modified

 > file /Library/Frameworks/iTunesLibrary.framework/Versions/A/iTunesLibrar*
/Library/Frameworks/iTunesLibrary.framework/Versions/A/iTunesLibrary: Mach-O 64-bit dynamically linked shared library x86_64

**Comment by DG12** [comment] 2016-09-10 15:13
/Applications > find . -name Japanese.lproj -ls |cut -c67-
     102 Dec 18  2015 ./Automator.app/Contents/Resources/Application Stub.app/Contents/Resources/Japanese.lproj
     646 Dec 18  2015 ./Automator.app/Contents/Resources/Japanese.lproj
     136 Jan 27  2016 ./Calendar.app/Contents/Resources/dayview.aplmodel/Contents/Resources/Japanese.lproj
     136 Jan 27  2016 ./Calendar.app/Contents/Resources/fullview.aplmodel/Contents/Resources/Japanese.lproj
    1836 Jan 27  2016 ./Calendar.app/Contents/Resources/Japanese.lproj
     136 Jan 27  2016 ./Calendar.app/Contents/Resources/monthview.aplmodel/Contents/Resources/Japanese.lproj
     136 Jan 27  2016 ./Calendar.app/Contents/Resources/selectedevents.aplmodel/Contents/Resources/Japanese.lproj
     136 Jan 27  2016 ./Calendar.app/Contents/Resources/weekview.aplmodel/Contents/Resources/Japanese.lproj
     306 Jun 10  2015 ./Chess.app/Contents/Resources/Japanese.lproj
    1258 May  4 03:07 ./Contacts.app/Contents/Resources/Japanese.lproj
     408 Jun 10  2015 ./Dictionary.app/Contents/Resources/Japanese.lproj
    1496 Dec 17  2015 ./DVD Player.app/Contents/Resources/Japanese.lproj
     884 Jan  4  2016 ./FaceTime.app/Contents/Resources/Japanese.lproj
    1598 Dec 19  2015 ./Font Book.app/Contents/Resources/Japanese.lproj
     238 Dec 18  2015 ./Image Capture.app/Contents/Resources/Japanese.lproj
     136 May  4 02:28 ./Messages.app/Contents/Frameworks/AVCore.framework/Versions/A/Resources/Japanese.lproj
     136 Jun 11  2015 ./Mission Control.app/Contents/Resources/Japanese.lproj
     272 Dec 18  2015 ./Photo Booth.app/Contents/Resources/Japanese.lproj
    1972 Dec 19  2015 ./Preview.app/Contents/Resources/Japanese.lproj
     918 Dec 18  2015 ./QuickTime Player.app/Contents/Resources/Japanese.lproj
     102 Sep  2 21:35 ./Safari.app/Contents/Resources/com.apple.Safari.manifest/Contents/Resources/Japanese.lproj
    2550 Sep  2 21:35 ./Safari.app/Contents/Resources/Japanese.lproj
     136 Sep  2 21:35 ./Safari.app/Contents/Resources/WelcomePage/Japanese.lproj
     272 Jun 11  2015 ./Stickies.app/Contents/Resources/Japanese.lproj
     204 Dec 19  2015 ./System Preferences.app/Contents/Resources/Japanese.lproj
     510 Feb 12  2016 ./TextEdit.app/Contents/Resources/Japanese.lproj
     102 Jun 11  2015 ./Time Machine.app/Contents/Resources/Japanese.lproj
     306 Dec 18  2015 ./Utilities/Activity Monitor.app/Contents/Resources/Japanese.lproj
     476 Dec 18  2015 ./Utilities/Audio MIDI Setup.app/Contents/Resources/Japanese.lproj
     272 Jun 21 17:12 ./Utilities/Bluetooth File Exchange.app/Contents/Resources/Japanese.lproj
     170 Jan 26  2016 ./Utilities/Boot Camp Assistant.app/Contents/Resources/Japanese.lproj
     136 Dec 18  2015 ./Utilities/ColorSync Utility.app/Contents/Resources/Calculator.csutil/Contents/Resources/Japanese.lproj
     136 Dec 18  2015 ./Utilities/ColorSync Utility.app/Contents/Resources/Devices.csutil/Contents/Resources/Japanese.lproj
     136 Dec 18  2015 ./Utilities/ColorSync Utility.app/Contents/Resources/Filters.csutil/Contents/Resources/Japanese.lproj
     170 Dec 18  2015 ./Utilities/ColorSync Utility.app/Contents/Resources/FirstAid.csutil/Contents/Resources/Japanese.lproj
     850 Dec 18  2015 ./Utilities/ColorSync Utility.app/Contents/Resources/Japanese.lproj
     136 Dec 18  2015 ./Utilities/ColorSync Utility.app/Contents/Resources/Profiles.csutil/Contents/Resources/Japanese.lproj
     476 Dec 18  2015 ./Utilities/Console.app/Contents/Resources/Japanese.lproj
     170 Dec 18  2015 ./Utilities/Digital Color Meter.app/Contents/Resources/Japanese.lproj
     340 Dec 19  2015 ./Utilities/Grab.app/Contents/Resources/Japanese.lproj
     952 Dec 19  2015 ./Utilities/Grapher.app/Contents/Resources/Japanese.lproj
     952 May 22 13:15 ./Utilities/Keychain Access.app/Contents/Resources/Japanese.lproj
     102 May 22 13:15 ./Utilities/Keychain Access.app/Contents/Resources/Keychain.menu/Contents/Resources/Japanese.lproj
     204 Dec 19  2015 ./Utilities/Migration Assistant.app/Contents/Resources/Japanese.lproj
     136 Dec 19  2015 ./Utilities/Migration Assistant.app/Contents/Resources/MigrationAssistantUI.bundle/Contents/Resources/Japanese.lproj
     136 Dec 19  2015 ./Utilities/Script Editor.app/Contents/PlugIns/DictionaryViewer.seplugin/Contents/Resources/Japanese.lproj
     136 Dec 19  2015 ./Utilities/Script Editor.app/Contents/PlugIns/Library.seplugin/Contents/Resources/Japanese.lproj
     102 Dec 19  2015 ./Utilities/Script Editor.app/Contents/PlugIns/ScriptManager.seplugin/Contents/Resources/Japanese.lproj
    1020 Dec 19  2015 ./Utilities/Script Editor.app/Contents/Resources/Japanese.lproj
     612 Dec 18  2015 ./Utilities/System Information.app/Contents/Resources/Japanese.lproj
     782 Dec 19  2015 ./Utilities/Terminal.app/Contents/Resources/Japanese.lproj
     102 Feb 16  2016 ./Utilities/VoiceOver Utility.app/Contents/Resources/com.apple.screenreaderd.manifest/Contents/Resources/Japanese.lproj
    1122 Feb 16  2016 ./Utilities/VoiceOver Utility.app/Contents/Resources/Japanese.lproj



PS I just found ~/Library/Logs/Monolingual.log  (I'd been looking in /var/log syslog)

head Monolingual.log |cut -c1-67,9599-9650
Monolingual started at 9/3/16, 4:04 PM
Removing languages: ach.lproj Acoli.lproj af.lproj Afrikaans.lproj  Japanese.lproj ja_JP.lproj ja-JP.lproj jv.lproj Jav
Deleted files: 
Monolingual started at 9/3/16, 9:10 PM
Removing languages: ach.lproj Acoli.lproj af.lproj Afrikaans.lproj  Japanese.lproj ja_JP.lproj ja-JP.lproj jv.lproj Jav
Deleted files: 
Monolingual started at 9/3/16, 9:12 PM
Removing architectures:  arm ppc ppc750 ppc7400 ppc7450 ppc970 ppc6
Modified files:
/Library/Application Support/iLifeMediaBrowser/Plug-Ins/iLMBApertur

**Comment by IngmarStein** [comment] 2016-09-12 06:37
If you're on Sierra, you could try the current HEAD. Running `sudo ./com.github.IngmarStein.Monolingual.Helper -i /Applications -d Japanese.lproj` seems to remove all files you mention above just fine on a system with SIP disabled.

**Comment by IngmarStein** [comment] 2016-12-14 15:46
Can you test again with 1.7.4?

**Comment by IngmarStein** [comment] 2017-01-09 09:22
Closed due to lack of feedback. Please reopen if this is still an issue with the current release.

**Closed by IngmarStein** 2017-01-09 09:22 UTC
