### ISSUE TITLE
Keeps asking for password when installing helper tool

### ISSUE THREAD

**Issue by dchandan** [IngmarStein/Monolingual#61] opened 2015-11-14 21:55 UTC
Monolingual keeps asking for password in order to install its helper tool. It can't proceed any further. I have tried version 1.7.2 1.7.0 and 1.6.7 and all have this issue. Monolingual used to work fine for years but recently i upgraded to El Capitan and upgraded the Monolingual version so I can't pin point where the problem started.

**Comment by IngmarStein** [comment] 2015-11-19 20:14
Duplicate of #48

**Closed by IngmarStein** 2015-11-19 20:14 UTC
Labels: duplicate
