### ISSUE TITLE
Monolingual 1.8.0 does nothing

### ISSUE THREAD

**Issue by objjg** [IngmarStein/Monolingual#134] opened 2018-04-04 15:32 UTC
I accepted the new version 1.8.0 but after the last MacOS update it did nothing. I went back to 1.7.8 and it removed over 175 megs of languages. 1.8.0 obviously has issues.

**Comment by billearl** [comment] 2018-04-12 19:54
Not true per Ingmar Stein, but agree with the perception that it is not doing anything. The issue is only with reporting.

IngmarStein commented 24 days ago: "Please note that this only affects reporting (updating the UI with the currently processed files, writing the log file, and presenting the total size), not the actual operation of the app itself."

**Comment by objjg** [comment] 2018-04-12 23:47
After accepting 1.8.0 and running there was no appreciable reduction in data on the disk. Monolingual only stated 1Kb removed. When checking a couple of the language locations it was clear nothing was removed. 1.7.8 performed as previously stated and I'm still bypassing 1.8.0. 

Possibly this has something to do with an APFS formatted drives not releasing/assigning previously released data, which is still occurring even though Apple swears they fix this.

**Comment by IngmarStein** [comment] 2018-04-13 04:04
It has nothing to do with APFS. 1.8.0 changed the way status updates are communicated from the helper to the UI. Apple has introduced a nice way to use `NSProgress` with XPC services, but it has limitations I was not aware of (the `userInfo` dictionary is unavailable - radar https://bugreport.apple.com/web/?problemID=38600258),

**Comment by BrianOliverSophie** [comment] 2018-04-19 23:14
Mine just disappears when I click Relaunch and Install and never updates.

**Comment by Arclightjake** [comment] 2018-04-27 00:10
I was happy to download an update that didn't tell me that it couldn't load the helper tool. Unfortunately, now it tells me that it removes 1 byte whenever I run it. It appears to do nothing at all now as there is no apparent change in file sizes after I run it.

**Comment by billearl** [comment] 2018-06-04 04:11
A Monolingual update to address this issue would be nice...

**Comment by dchandan** [comment] 2018-08-23 18:35
Version 1.8.0 does not remove the language files from all apps. I think it does remove from some apps, but not from all. In my case the app runs for just under 30 seconds and reports that it has finished. As shown in the pic below, after completion, language files remained in Acrobat Reader DC.
<img width="667" alt="screen shot 2018-08-23 at 12 32 56 pm" src="https://user-images.githubusercontent.com/5779123/44544991-06f69880-a6d1-11e8-8b98-f852c61d919a.png">

**Comment by IngmarStein** [comment] 2019-02-10 21:35
I hope this is fixed with 1.8.2.

**Closed by IngmarStein** 2019-02-10 21:35 UTC

**Comment by Arclightjake** [comment] 2019-02-11 00:32
It was NOT fixed with 1.8.2.

**Comment by objjg** [comment] 2019-02-11 00:45
Be sure that 1.8.2. is actually replacing the old version. I discovered it did not in my download. It left the old version in place. I had to remove it and then download the new 1.8.2. and it then worked.

**Comment by Arclightjake** [comment] 2019-02-11 00:59
Good tip. It took a little effort to find and erase ALL the files from the preceding version, but I got there. Appears to work fine now.  

Thank you.

**Comment by IngmarStein** [comment] 2019-02-11 07:11
I'm curious what happened. Did the new version not ask you to upgrade the installed helper?

**Comment by Arclightjake** [comment] 2019-02-11 11:16
No, it did not. I Used a dedicated app to find all the associated files and
erased them. Then I found a couple more that the app had not uncovered. I
restarted after emptying the trash. I then did a clean download from your
site, unpacked it, and did the install. Before trying to use it, I
restarted. It worked as expected on the first use. I never got a prompt to
update the helper.

**Comment by objjg** [comment] 2019-02-11 15:37
I started 1.7.8 and selected “Check for updates” 1.8.2 downloaded and asked to “install and restart” which I clicked and it disappeared. When I check MONO.. it was still 1.7.8. The new version didn’t replace it. 

I had to delete 1.7.8 manually, (luckily I have CleanMyMac which removes everything) I then downloaded and installed 1.8.2 manually. After that it was fine.

Mike;
