### ISSUE TITLE
Compatibility with El Capitan and Office 2011 / Office 2016

### ISSUE THREAD

**Issue by fhazan001** [IngmarStein/Monolingual#53] opened 2015-10-07 19:30 UTC
After running monolingual - the entire Office product is rendered useless and must be completely uninstalled and reinstalled.   The message it gives relates to a missing file which are incorrectly removed.   If it happens again I will post the specific message.

**Comment by IngmarStein** [comment] 2015-10-08 19:26
Duplicate of #43

**Closed by IngmarStein** 2015-10-08 19:26 UTC
Labels: duplicate
