### ISSUE TITLE
Helper add-in w/1.72

### ISSUE THREAD

**Issue by Wallyec** [IngmarStein/Monolingual#48] opened 2015-10-05 14:24 UTC
Not able to load HELPER - so program does not load??
running 10.11.1 beta

**Comment by IngmarStein** [comment] 2015-10-05 19:32
Could you please check if ```sudo launchctl print-disabled system``` includes "com.github.IngmarStein.Monolingual.Helper"?
In that case, the output looks like
```
disabled services = {
	…
	"com.github.IngmarStein.Monolingual.Helper" => true
	…
```
Monolingual 1.7.0 and 1.7.1 had a bug which added the helper to list of disabled services when updating it to a newer version. In that case, the following command (maybe followed by a reboot) should fix the issue:
```
sudo launchctl load -w /Library/LaunchDaemons/com.github.IngmarStein.Monolingual.Helper.plist
```

**Comment by jcmjgit** [comment] 2015-10-06 13:53
Not in there, as you can see. 

![schermafbeelding 2015-10-06 om 15 51 33](https://cloud.githubusercontent.com/assets/14997176/10310412/28eeb304-6c42-11e5-9ed6-f116cc6b8708.png)

**Comment by Buminthewoods** [comment] 2015-10-09 00:31
Failure to load Helper from 1.7.2 confirmed under El Capitan 10.11 (15A284) with SIP (csrutil) disabled, even though there were NO pre-existing references anywhere to "monolingual" or "IngmarStein".

**Comment by tladesignz** [comment] 2015-10-16 08:10
Had the same issue. That's a problem for end users they won't circumnavigate. Can you add the re-enabling into Monolingual itself?

**Comment by IngmarStein** [comment] 2015-10-16 15:28
In case any Apple employees stumble upon this: I've filed bug number 23143866 for this. This issue can even be reproduced with Apple sample code and seems to be new on El Capitan.

**Comment by KaleoK** [comment] 2015-10-21 19:03
Tried that. Did not work. What to do?

"Failure to load Helper from 1.72 confirmed under El Capitan 10.11 (15A284) with SIP (csrutil) disabled, even though there were NO pre-existing references anywhere to "monolingual" or "IngmarStein".

Fresh install of 1.72 then removing the helper from the disabled services list solved the problem."

**Comment by Mike-BITW** [comment] 2015-10-21 20:25
Simply follow @IngmarStein's instructions from a few comments above:

>_sudo launchctl load -w /Library/LaunchDaemons/com.github.IngmarStein.Monolingual.Helper.plist_

then reboot (optional but recommended0 and try Monolingual again.

**Comment by KaleoK** [comment] 2015-10-21 21:14
Had tried that already. Get a no such file or directory response.

**Comment by andos17** [comment] 2015-10-28 12:06
Helper doesn't load for me also under 10.11.1 and commands don't work in terminal this is what I get sudo: unable to stat /etc/sudoers: Permission denied
sudo: no valid sudoers sources found, quitting

**Comment by Mike-BITW** [comment] 2015-10-28 13:26
That's unrelated to Monolingual.  Either your permissions are set wrong (probably)  or /etc/sudoers is actually missing (unlikely). Let Google be your guide... ;)

**Comment by andos17** [comment] 2015-10-29 04:21
Doesn't list helper in service list can I load it manually and how do I do that? will it work if I completely disable system protection? only have without debug, was working with 10.10 and was working until update 1.72 and if I install an old version still won't load helper. If I do your fix from recovery drive will it work then??

**Comment by IngmarStein** [comment] 2015-11-03 05:37
My bug report for Apple has been closed as a duplicate of bug 19601397. However, hey provided me with the following information:

> Hi Ingmar,
> 
> I've confirmed with OS X Engineering that this is a bug that we'll need to fix on our end. There is no workaround available.
> 
> Please continue to follow up with your bug report to track its progress or to provide more information to OS X Engineering.
> 
> Best regards

**Comment by andos17** [comment] 2015-11-03 07:14
At least it's not just me, hope for a fix soon. As all your workarounds don't work for me it's since apple update to 10.11.1 and your update 1.72. Tried putting back the version that did work and prefs with no joy might try SIP completely disabled some apps will run with it off!

**Comment by jcmjgit** [comment] 2015-11-03 08:20
Ingmar, As I wrote before : A clean install ( meaning removing ALL Monolingual files) and a restart worked
for me. Removing all files can be done by searching with for example: Find Any File.

"Je voetbalt met je hoofd en loopt op je benen." Johan Cruyff
Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.2]
On di, nov. 3, 2015 at 6:37 a.m., IngmarStein/Monolingual
<reply@reply.github.com>
wrote:
My bug report for Apple has been closed as a duplicate of bug 19601397. However,
hey provided me with the following information:

Hi Ingmar,

I've confirmed with OS X Engineering that this is a bug that we'll need to fix
on our end. There is no workaround available.

Please continue to follow up with your bug report to track its progress or to
provide more information to OS X Engineering.

Best regards

—
Reply to this email directly or view it on GitHub
[https://github.com/IngmarStein/Monolingual/issues/48#issuecomment-153247103] .[https://github.com/notifications/beacon/AOTWuK1h98JbalRA7SEPCHLx2NBOLD0Xks5pCD-GgaJpZM4GJBX_.gif]

**Comment by andos17** [comment] 2015-11-03 08:30
I did a clean install didn't work, do I need to disable SIP first?

**Comment by IngmarStein** [comment] 2015-11-03 08:52
This issue is not related to SIP. You can leave it on.
The bug in OS X is that there are some situations where it doesn't tell the app (Monolingual) when the privileged helper is missing on the filesystem. That check just never returns and Monolingual waits for the result indefinitely.
A clean install with a restart sometimes resolves that situation.

**Comment by andos17** [comment] 2015-11-06 11:33
Got rid of all the old files a clean install restart still no joy!

**Comment by IngmarStein** [comment] 2016-12-14 15:53
Cleaning old tickets.

**Closed by IngmarStein** 2016-12-14 15:53 UTC
