### ISSUE TITLE
Monolingual 1.6

### ISSUE THREAD

**Issue by mckmeper** [IngmarStein/Monolingual#3] opened 2014-10-26 03:12 UTC
"Monolingual is trying to install a helper tool" but it never installs apparently and the application cannot be used.

**Comment by IngmarStein** [comment] 2015-03-30 05:08
Is this still an issue in 1.6.6?

**Comment by mckmeper** [comment] 2015-03-30 08:25
I am experiencing the same behavior. I removed the old helper and started
1.6.6. I keeps telling me it is trying to install a new helper and never
actually begins the language file removals.

**Comment by IngmarStein** [comment] 2015-03-30 08:29
Could you please have a look at the console and send me Monolingual's output when you try to start the removal process? It should look like the following:

    30.03.15 10:27:17,053 Monolingual[21726]: net.sourceforge.MonolingualHelper (1.6.6) is already current, skipping install.

**Comment by mckmeper** [comment] 2015-03-30 08:51
I hope this is what you want

**Comment by IngmarStein** [comment] 2015-03-30 09:07
It seems like GitHub has filtered your attachment…

**Comment by IngmarStein** [comment] 2015-03-31 06:38
Could you please send the output again?

**Comment by mckmeper** [comment] 2015-03-31 08:27
Sure, here's the one I saved from yesterday:

**Comment by IngmarStein** [comment] 2015-03-31 08:33
Please have a look at https://github.com/IngmarStein/Monolingual/issues/3#issuecomment-87993723, there are no attachments there.

**Comment by mckmeper** [comment] 2015-04-02 21:48
Hello Ingmar,

Strangely, I have Monolingual 1.6.6 installed on an external drive running
the Public Beta 10.10.3 and Monolingual runs fine. Go figure.

**Comment by IngmarStein** [comment] 2015-04-05 13:36
Is this still an issue with 1.6.7?

**Comment by mckmeper** [comment] 2015-04-05 17:50
Yes, no change. I am still required to type my password while Monolingual
creates a new helper file then nothing happens. I'm beginning to think that
another application is interfering with Monolingual but it operates the
same in "Safe Mode."

**Comment by IngmarStein** [comment] 2015-04-06 14:22
I'm going to close this as a duplicate of #1. Could you please follow the instructions there (please don't send mail attachments - GitHub filters them):

> Ok, I'll try to fix that password prompt. You could help me by providing the console output again (you can leave out all those "Blacklisting…" lines). Here's how it should look:
> 
> First time:
05.04.15 15:40:27,310 Monolingual[92636]: net.sourceforge.MonolingualHelper (1.6.7) installed successfully
> 
> Subsequent launches:
> 05.04.15 15:41:22,406 Monolingual[92665]: net.sourceforge.MonolingualHelper (1.6.7) is already current, skipping install.

**Closed by IngmarStein** 2015-04-06 14:22 UTC
Labels: help wanted

**Comment by mckmeper** [comment] 2015-04-06 17:24
I've copied and pasted what seem to be the relevant lines. Hope this helps.

4/6/15 10:18:35.823 AM com.apple.xpc.launchd[1]:
(com.apple.xpc.launchd.domain.system) Caller specified a plist with bad
ownership/permissions: path =
/Library/LaunchDaemons/net.sourceforge.MonolingualHelper.plist, caller =
smd.277
4/6/15 10:18:35.826 AM Monolingual[34104]: [SMJKit Error] SMJobBless
failure (code 2): The operation couldn’t be completed.
(CFErrorDomainLaunchd error 2.)
4/6/15 10:18:35.826 AM Monolingual[34104]: Failed to bless helper. Error:
Error Domain=SMJobKit Code=1010 "SMJobBless failure (code 2): The operation
couldn’t be completed. (CFErrorDomainLaunchd error 2.)"
UserInfo=0x600000226120 {NSLocalizedDescription=SMJobBless failure (code
2): The operation couldn’t be completed. (CFErrorDomainLaunchd error 2.)}

**Comment by IngmarStein** [comment] 2015-04-07 11:17
Could you please delete /Library/PrivilegedHelperTools/net.sourceforge.MonolingualHelper and try again? launchd in Yosemite can get into a state in which it refuses to install a privileged helper until you delete it. Even Apple's sample code exhibits the problem and I've filed rdar://problem/20446733

**Comment by mckmeper** [comment] 2015-04-07 17:54
I have deleted the specified tool and the behavior is the same: Each time I
launch Monolingual 1.6.7 I am asked to type my password so Monolingual can
install a new helper tool. And each time it installs a new helper over the
old one, but the application does not display any signs that it is
functioning.

**Comment by IngmarStein** [comment] 2015-04-07 18:05
Yeah, this happens when launchd is confused about the state of the helper and just returns an "internal error" to the application.
Please try the following script and try again:
```
sudo rm /Library/LaunchDaemons/net.sourceforge.MonolingualHelper.plist
sudo rm /Library/PrivilegedHelperTools/net.sourceforge.MonolingualHelper
sudo launchctl stop net.sourceforge.MonolingualHelper
sudo launchctl remove net.sourceforge.MonolingualHelper
```

**Comment by mckmeper** [comment] 2015-04-07 19:18
That did it. It's working! Removed 1.29G. Started it up again and no
request. Thanks Ingmar, it's great to have Monolingual back again.

**Comment by mckmeper** [comment] 2015-09-24 05:29
1.7.1 has broken 1.7.0 and completely deleting 1.7.0 and re-installing
1.7.1 does not solve the dilemma. No helper file to be found. And the sudos
from a previous session with 1.6.7 is being repeated.

Mike Kemper
