### ISSUE TITLE
Monolingual 1.7.1 broke 1.7.0

### ISSUE THREAD

**Issue by mckmeper** [IngmarStein/Monolingual#45] opened 2015-09-24 05:33 UTC
Installing 1.7.1 has yeilded an app that just sits there. No message about a new helper. Nothing. Uninstalling and reinstalling 1.7.0 resulted in the same behavior as 1.7.1. Monolingual's dead on this machine.

**Comment by IngmarStein** [comment] 2015-09-24 06:43
OS X 10.10.x has a bug when updating privileged helpers which Apple has fixed in 10.11 (Radar 20446733, fix was included in El Capitan Beta 3). In the meantime, you can try the following - the helper ID has changed in Monolingual 1.7.0.
```
sudo rm /Library/LaunchDaemons/com.github.IngmarStein.Monolingual.Helper.plist
sudo rm /Library/PrivilegedHelperTools/com.github.IngmarStein.Monolingual.Helper
sudo launchctl stop com.github.IngmarStein.Monolingual.Helper
sudo launchctl remove com.github.IngmarStein.Monolingual.Helper
```

**Comment by mckmeper** [comment] 2015-09-24 10:40
Hello,

I have followed the Terminal commands you sent and have the same result. In
addition I do not find the files indicated in either the LaunchDaemons
folder or the PrivilegedHelperTools folder after replacing 1.7.1 with 1.7.0

**Comment by unsureone** [comment] 2015-09-24 16:27
I had the same problem with 1.7.1 under OS X 10.10.5, reverted to Monolingual 1.7.0, and also didn't see the helper message anymore on 1.7.0. However, rebooting and then trying 1.7.0 again brought the helper message back on that version for me.

**Comment by mckmeper** [comment] 2015-09-24 17:19
Restart solved the problem. Thanks, David.

**Comment by IngmarStein** [comment] 2015-09-24 17:37
Yes, you've unfortunately triggered the OS X bug mentioned above and a restart works around it. I'll probably increase the minimum version of Monolingual 1.7.x to 10.11. Versions earlier than 1.7 used to uninstall the helper before installing a new version but that API is deprecated and it caused two authentication prompts.

**Comment by unsureone** [comment] 2015-09-25 22:50
Under OS X 10.10.5, I hadn't tried Ingmar's Terminal commands under 1.7.1 before reverting to 1.7.0, so I installed 1.7.1 and gave them a try. As mckmeper experienced, the specified "Helper" and "Helper.plist" files did not return, and restarts did not make a difference. That is, there was no request to install a Helper, and Monolingual didn't display a progress window. (Is it silently removing localizations while appearing to do nothing? I don't know.)

I further tried removing the "net.sourceforge.MonolingualHelper.plist" file from Library/LaunchDaemons and "net.sourceforge.MonolingualHelper" file from Library/PrivilegedHelperTools (apparently left over from Monolingual 1.6.7). That, too, with restarts, made no visible difference.

So, unless there's some other solution, reverting to 1.7.0 appears to be necessary under 10.10.5.

**Comment by KaleoK** [comment] 2015-09-28 19:38
First, had an error message in 1.7.0 that the update failed to download. Went to the website and downloaded 1.7.1. Now, have the error message: Failed to Install Helper Utility.

This is with El Capitan 10.11.1 on a MacBook Air.

Fix it, please!

**Comment by IngmarStein** [comment] 2015-09-28 19:43
The update failure should be resolved when Amazon S3 (which hosts GitHub releases) switches from SHA1 to SHA256 for their SSL certificates. This is supposed to happen on September 30, just in time for the official El Capitan release. The error is related to the new App Transport Security feature of 10.11.

Stop posting issues for beta builds of OS X, please!

**Comment by mckmeper** [comment] 2015-10-04 04:33
Hello Ingmar,

Monolingual 1.7.1 is running on Mac OS 10.11, however it says it's removing
Vietnamese localizations every time I run it and if I run it immediately
after it has run saying it has removed 41.7 mb of localizations it removes
41,7 mb again. Either it's not removing the Vietnamese (and some Japanese)
or just keeps saying it is.

**Comment by IngmarStein** [comment] 2015-10-04 10:51
There are now three different items in this issue:
1) a problem updating from 1.7.0 to 1.7.1
2) a problem downloading updates on El Capitan (related to App Transport Security and Amazon S3)
3) a reporting issue related to SIP on El Capitan

Nr. 1 is hopefully fixed in 10.11. I've increased the minimum system version accordingly for 1.7.2.
Nr. 2 should be fixed by Amazon soon (see https://forums.aws.amazon.com/thread.jspa?messageID=678126)
Nr. 3 is a duplicate of #46

**Comment by IngmarStein** [comment] 2016-12-14 15:50
Cleaning old tickets.

**Closed by IngmarStein** 2016-12-14 15:50 UTC

**Comment by Arclightjake** [comment] 2018-04-12 22:30
I have never been able to get any version of Monolingual to run after 1.6.7. I'm on a mid-2015, MacBook Pro 15", running OS 10.13.4. I've tried the posted terminal commands and they did nothing.
