### ISSUE TITLE
in 10.14, Monolingual is working, but display is broken

### ISSUE THREAD

**Issue by readingsnail** [IngmarStein/Monolingual#137] opened 2018-07-12 00:40 UTC
well, in 10.14 PB2, Currently Monolingual is working well.

<img width="340" alt="2018-07-12 9 39 03" src="https://user-images.githubusercontent.com/1904967/42606250-7169a9f4-85b7-11e8-8099-ea81d67e79ea.png">

i think it's apple's fault, but big problem is monolingual is well working, but it's show 'earn 1 bytes's free space'

it's same language and arch, so maybe need fixing them

**Comment by IngmarStein** [comment] 2018-07-12 06:18
Duplicate of #134

**Closed by IngmarStein** 2018-07-12 06:18 UTC
